###
http://127.0.0.1:3000/
http://127.0.0.1:3000/api/user/1
http://127.0.0.1:3000/app/user/tes
http://127.0.0.1:3000/




### Ver todos los usuarios
GET http://127.0.0.1:3000/api/user/

### Ver solo 1 usuario
GET http://127.0.0.1:3000/api/user/search/user@example.com


### -> crear un nuevo usuario
POST http://127.0.0.1:3000/api/register
Content-Type: application/json

{
  "email": "user@example.com",
  "username": "user123",
  "password": "pass1234",
  "role": "company",
  "companyDetails": {
    "name": "TechCorp",
    "address": "123 Tech Street, New York, NY",
    "website": "https://techcorp.com"
  }
}


### -> actualizar usuarios
put http://127.0.0.1:3000/api/user/update/user@example.com
Content-Type: application/json

{
  "email": "user1@example.com",
  "username": "usuarioactualizado",
  "password": "pass123",
  "role": "company",
  "companyDetails": {
    "name": "TechCorp",
    "address": "123 Tech Street, New York, NY",
    "website": "https://techcorp.com"
  }
}